apiVersion: v1
kind: Service
metadata:
  name: github-cicd-demo
  namespace: github-cicd-demo
spec:
  selector:
    app: github-cicd-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-cicd-demo
  namespace: github-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: github-cicd-demo
  template:
    metadata:
      labels:
        app: github-cicd-demo
    spec:
      containers:
        - name: github-cicd-demo
          image: 226503510091.dkr.ecr.ap-northeast-1.amazonaws.com/github-cicd-demo:latest
          ports:
            - containerPort: 80